tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "docker"
brew "git"
brew "mariadb"
brew "nginx"
brew "python@2", link: false
brew "watchman"
brew "yarn"
brew "zsh"
cask "font-fira-code"
